credentials:
  usernames:
    johndoe:
      email: johndoe@example.com
      name: John Doe
      password: "hashed_password_for_johndoe"
    janedoe:
      email: janedoe@example.com
      name: Jane Doe
      password: "hashed_password_for_janedoe"
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name