name: CI/CD Pipeline for Resume Analyzer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      # Use the same Docker image as specified in devcontainer.json
      image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system packages (if packages.txt exists)
        run: |
          if [ -f packages.txt ]; then
            sudo apt update && sudo apt upgrade -y
            sudo xargs -a packages.txt apt install -y
          fi

      - name: Set up Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit

      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add test commands here (e.g., pytest, unittest)
          pytest || echo "No tests found or failed."

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    container:
      # Use the same Docker image as specified in devcontainer.json
      image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system packages (if packages.txt exists)
        run: |
          if [ -f packages.txt ]; then
            sudo apt update && sudo apt upgrade -y
            sudo xargs -a packages.txt apt install -y
          fi

      - name: Set up Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit

      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Deploy the app
        run: |
          echo "Deploying the app ..."
          nohup streamlit run streamlit_app.py --server.enableCORS false --server.enableXsrfProtection false > app.log 2>&1 &
          echo "Streamlit app started. Logs are being written to app.log."